version: "3"

services:
  ros2:
    build: .
    container_name: ros2_safemode
    network_mode: host
    restart: always
    privileged: true

    environment:
      - ROS_DOMAIN_ID=52
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - "/home/util/ProjetDrone/m_safemode/ros_ws:/root/ros_ws"
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true

    command: >
      bash -c "
      source /opt/ros/jazzy/setup.bash &&
      python3 /root/ros_ws/src/mode/robot_mode_manager.py
      "
